// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const approveAction = `-- name: ApproveAction :exec
UPDATE recovery_actions
SET status = 'APPROVED', approved_by_clerk_id = $2, payment_link_id = $3, payment_link_url = $4
WHERE id = $1
`

type ApproveActionParams struct {
	ID                uuid.UUID      `json:"id"`
	ApprovedByClerkID sql.NullString `json:"approved_by_clerk_id"`
	PaymentLinkID     sql.NullString `json:"payment_link_id"`
	PaymentLinkUrl    sql.NullString `json:"payment_link_url"`
}

func (q *Queries) ApproveAction(ctx context.Context, arg ApproveActionParams) error {
	_, err := q.db.ExecContext(ctx, approveAction,
		arg.ID,
		arg.ApprovedByClerkID,
		arg.PaymentLinkID,
		arg.PaymentLinkUrl,
	)
	return err
}

const createRecoveryAction = `-- name: CreateRecoveryAction :one
INSERT INTO recovery_actions (
    recovery_case_id, idempotency_key, action_type, channel, 
    ai_reasoning, discount_percentage, draft_payload, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateRecoveryActionParams struct {
	RecoveryCaseID     uuid.UUID             `json:"recovery_case_id"`
	IdempotencyKey     string                `json:"idempotency_key"`
	ActionType         ActionType            `json:"action_type"`
	Channel            sql.NullString        `json:"channel"`
	AiReasoning        sql.NullString        `json:"ai_reasoning"`
	DiscountPercentage sql.NullInt32         `json:"discount_percentage"`
	DraftPayload       pqtype.NullRawMessage `json:"draft_payload"`
	Status             ActionStatus          `json:"status"`
}

func (q *Queries) CreateRecoveryAction(ctx context.Context, arg CreateRecoveryActionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRecoveryAction,
		arg.RecoveryCaseID,
		arg.IdempotencyKey,
		arg.ActionType,
		arg.Channel,
		arg.AiReasoning,
		arg.DiscountPercentage,
		arg.DraftPayload,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActionByIdempotencyKey = `-- name: GetActionByIdempotencyKey :one
SELECT id, status FROM recovery_actions WHERE idempotency_key = $1 LIMIT 1
`

type GetActionByIdempotencyKeyRow struct {
	ID     uuid.UUID    `json:"id"`
	Status ActionStatus `json:"status"`
}

func (q *Queries) GetActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetActionByIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getActionByIdempotencyKey, idempotencyKey)
	var i GetActionByIdempotencyKeyRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getActionsByCase = `-- name: GetActionsByCase :many
SELECT id, action_type, channel, status, ai_reasoning, draft_payload, discount_percentage, executed_at, created_at
FROM recovery_actions
WHERE recovery_case_id = $1
ORDER BY created_at DESC
`

type GetActionsByCaseRow struct {
	ID                 uuid.UUID             `json:"id"`
	ActionType         ActionType            `json:"action_type"`
	Channel            sql.NullString        `json:"channel"`
	Status             ActionStatus          `json:"status"`
	AiReasoning        sql.NullString        `json:"ai_reasoning"`
	DraftPayload       pqtype.NullRawMessage `json:"draft_payload"`
	DiscountPercentage sql.NullInt32         `json:"discount_percentage"`
	ExecutedAt         sql.NullTime          `json:"executed_at"`
	CreatedAt          time.Time             `json:"created_at"`
}

func (q *Queries) GetActionsByCase(ctx context.Context, recoveryCaseID uuid.UUID) ([]GetActionsByCaseRow, error) {
	rows, err := q.db.QueryContext(ctx, getActionsByCase, recoveryCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActionsByCaseRow
	for rows.Next() {
		var i GetActionsByCaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Channel,
			&i.Status,
			&i.AiReasoning,
			&i.DraftPayload,
			&i.DiscountPercentage,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingActions = `-- name: GetPendingActions :many
SELECT id, recovery_case_id, action_type, channel, ai_reasoning, discount_percentage, draft_payload
FROM recovery_actions
WHERE status = 'PENDING_APPROVAL'
ORDER BY created_at ASC
`

type GetPendingActionsRow struct {
	ID                 uuid.UUID             `json:"id"`
	RecoveryCaseID     uuid.UUID             `json:"recovery_case_id"`
	ActionType         ActionType            `json:"action_type"`
	Channel            sql.NullString        `json:"channel"`
	AiReasoning        sql.NullString        `json:"ai_reasoning"`
	DiscountPercentage sql.NullInt32         `json:"discount_percentage"`
	DraftPayload       pqtype.NullRawMessage `json:"draft_payload"`
}

func (q *Queries) GetPendingActions(ctx context.Context) ([]GetPendingActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingActionsRow
	for rows.Next() {
		var i GetPendingActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecoveryCaseID,
			&i.ActionType,
			&i.Channel,
			&i.AiReasoning,
			&i.DiscountPercentage,
			&i.DraftPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionExecuted = `-- name: MarkActionExecuted :exec
UPDATE recovery_actions
SET status = 'EXECUTED', external_id = $2, executed_at = NOW()
WHERE id = $1
`

type MarkActionExecutedParams struct {
	ID         uuid.UUID      `json:"id"`
	ExternalID sql.NullString `json:"external_id"`
}

func (q *Queries) MarkActionExecuted(ctx context.Context, arg MarkActionExecutedParams) error {
	_, err := q.db.ExecContext(ctx, markActionExecuted, arg.ID, arg.ExternalID)
	return err
}

const rejectAction = `-- name: RejectAction :exec
UPDATE recovery_actions
SET status = 'REJECTED', approved_by_clerk_id = $2
WHERE id = $1
`

type RejectActionParams struct {
	ID                uuid.UUID      `json:"id"`
	ApprovedByClerkID sql.NullString `json:"approved_by_clerk_id"`
}

func (q *Queries) RejectAction(ctx context.Context, arg RejectActionParams) error {
	_, err := q.db.ExecContext(ctx, rejectAction, arg.ID, arg.ApprovedByClerkID)
	return err
}

const updateActionAsynqTask = `-- name: UpdateActionAsynqTask :exec
UPDATE recovery_actions
SET asynq_task_id = $2
WHERE id = $1
`

type UpdateActionAsynqTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	AsynqTaskID sql.NullString `json:"asynq_task_id"`
}

func (q *Queries) UpdateActionAsynqTask(ctx context.Context, arg UpdateActionAsynqTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateActionAsynqTask, arg.ID, arg.AsynqTaskID)
	return err
}

const updateActionDraft = `-- name: UpdateActionDraft :exec
UPDATE recovery_actions
SET draft_payload = $2, human_edited = TRUE
WHERE id = $1
`

type UpdateActionDraftParams struct {
	ID           uuid.UUID             `json:"id"`
	DraftPayload pqtype.NullRawMessage `json:"draft_payload"`
}

func (q *Queries) UpdateActionDraft(ctx context.Context, arg UpdateActionDraftParams) error {
	_, err := q.db.ExecContext(ctx, updateActionDraft, arg.ID, arg.DraftPayload)
	return err
}
