// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (source_binary, event_type, actor, trace_id, entity_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	SourceBinary string          `json:"source_binary"`
	EventType    string          `json:"event_type"`
	Actor        sql.NullString  `json:"actor"`
	TraceID      uuid.NullUUID   `json:"trace_id"`
	EntityID     sql.NullString  `json:"entity_id"`
	Payload      json.RawMessage `json:"payload"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.SourceBinary,
		arg.EventType,
		arg.Actor,
		arg.TraceID,
		arg.EntityID,
		arg.Payload,
	)
	return err
}
