// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRecoveryCase = `-- name: CreateRecoveryCase :one
INSERT INTO recovery_cases (
    customer_id, subscription_id, payment_id, razorpay_error_code, 
    razorpay_error_desc, amount_at_risk, currency, first_failed_at, recovery_deadline
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW() + INTERVAL '14 days'
)
RETURNING id
`

type CreateRecoveryCaseParams struct {
	CustomerID        uuid.NullUUID  `json:"customer_id"`
	SubscriptionID    string         `json:"subscription_id"`
	PaymentID         sql.NullString `json:"payment_id"`
	RazorpayErrorCode sql.NullString `json:"razorpay_error_code"`
	RazorpayErrorDesc sql.NullString `json:"razorpay_error_desc"`
	AmountAtRisk      int64          `json:"amount_at_risk"`
	Currency          string         `json:"currency"`
}

func (q *Queries) CreateRecoveryCase(ctx context.Context, arg CreateRecoveryCaseParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRecoveryCase,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.PaymentID,
		arg.RazorpayErrorCode,
		arg.RazorpayErrorDesc,
		arg.AmountAtRisk,
		arg.Currency,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveCaseBySubscription = `-- name: GetActiveCaseBySubscription :one
SELECT id, status FROM recovery_cases
WHERE subscription_id = $1 AND status NOT IN ('RECOVERED', 'UNRECOVERABLE', 'EXPIRED')
LIMIT 1
`

type GetActiveCaseBySubscriptionRow struct {
	ID     uuid.UUID      `json:"id"`
	Status RecoveryStatus `json:"status"`
}

func (q *Queries) GetActiveCaseBySubscription(ctx context.Context, subscriptionID string) (GetActiveCaseBySubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCaseBySubscription, subscriptionID)
	var i GetActiveCaseBySubscriptionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getRecoveryCaseByID = `-- name: GetRecoveryCaseByID :one
SELECT id, customer_id, subscription_id, payment_id, razorpay_error_code, razorpay_error_desc, decline_category, ai_diagnosis, ai_confidence, status, retry_count, max_retries, contact_count, max_contacts, amount_at_risk, currency, amount_recovered, first_failed_at, recovery_deadline, recovered_at, next_retry_at, created_at, updated_at, ai_strategy FROM recovery_cases WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecoveryCaseByID(ctx context.Context, id uuid.UUID) (RecoveryCase, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryCaseByID, id)
	var i RecoveryCase
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.PaymentID,
		&i.RazorpayErrorCode,
		&i.RazorpayErrorDesc,
		&i.DeclineCategory,
		&i.AiDiagnosis,
		&i.AiConfidence,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ContactCount,
		&i.MaxContacts,
		&i.AmountAtRisk,
		&i.Currency,
		&i.AmountRecovered,
		&i.FirstFailedAt,
		&i.RecoveryDeadline,
		&i.RecoveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiStrategy,
	)
	return i, err
}

const listRecoveryCases = `-- name: ListRecoveryCases :many
SELECT id, customer_id, subscription_id, payment_id, razorpay_error_code, razorpay_error_desc, decline_category, ai_diagnosis, ai_confidence, status, retry_count, max_retries, contact_count, max_contacts, amount_at_risk, currency, amount_recovered, first_failed_at, recovery_deadline, recovered_at, next_retry_at, created_at, updated_at, ai_strategy FROM recovery_cases
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecoveryCasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecoveryCases(ctx context.Context, arg ListRecoveryCasesParams) ([]RecoveryCase, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveryCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryCase
	for rows.Next() {
		var i RecoveryCase
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.PaymentID,
			&i.RazorpayErrorCode,
			&i.RazorpayErrorDesc,
			&i.DeclineCategory,
			&i.AiDiagnosis,
			&i.AiConfidence,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ContactCount,
			&i.MaxContacts,
			&i.AmountAtRisk,
			&i.Currency,
			&i.AmountRecovered,
			&i.FirstFailedAt,
			&i.RecoveryDeadline,
			&i.RecoveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AiStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseDiagnosis = `-- name: UpdateCaseDiagnosis :exec
UPDATE recovery_cases
SET ai_diagnosis = $2, ai_confidence = $3, decline_category = $4, status = 'DIAGNOSING', updated_at = NOW()
WHERE id = $1
`

type UpdateCaseDiagnosisParams struct {
	ID              uuid.UUID       `json:"id"`
	AiDiagnosis     sql.NullString  `json:"ai_diagnosis"`
	AiConfidence    sql.NullFloat64 `json:"ai_confidence"`
	DeclineCategory NullDeclineType `json:"decline_category"`
}

func (q *Queries) UpdateCaseDiagnosis(ctx context.Context, arg UpdateCaseDiagnosisParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseDiagnosis,
		arg.ID,
		arg.AiDiagnosis,
		arg.AiConfidence,
		arg.DeclineCategory,
	)
	return err
}

const updateCaseRecovered = `-- name: UpdateCaseRecovered :exec
UPDATE recovery_cases
SET status = 'RECOVERED', amount_recovered = $2, recovered_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateCaseRecoveredParams struct {
	ID              uuid.UUID     `json:"id"`
	AmountRecovered sql.NullInt64 `json:"amount_recovered"`
}

func (q *Queries) UpdateCaseRecovered(ctx context.Context, arg UpdateCaseRecoveredParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseRecovered, arg.ID, arg.AmountRecovered)
	return err
}

const updateCaseStatus = `-- name: UpdateCaseStatus :exec
UPDATE recovery_cases
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCaseStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status RecoveryStatus `json:"status"`
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseStatus, arg.ID, arg.Status)
	return err
}

const updateCaseStrategy = `-- name: UpdateCaseStrategy :exec
UPDATE recovery_cases
SET ai_strategy = $2, status = 'RECOVERING', updated_at = NOW()
WHERE id = $1
`

type UpdateCaseStrategyParams struct {
	ID         uuid.UUID             `json:"id"`
	AiStrategy pqtype.NullRawMessage `json:"ai_strategy"`
}

func (q *Queries) UpdateCaseStrategy(ctx context.Context, arg UpdateCaseStrategyParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseStrategy, arg.ID, arg.AiStrategy)
	return err
}

const updateNextRetry = `-- name: UpdateNextRetry :exec
UPDATE recovery_cases
SET next_retry_at = $2, retry_count = retry_count + 1, updated_at = NOW()
WHERE id = $1
`

type UpdateNextRetryParams struct {
	ID          uuid.UUID    `json:"id"`
	NextRetryAt sql.NullTime `json:"next_retry_at"`
}

func (q *Queries) UpdateNextRetry(ctx context.Context, arg UpdateNextRetryParams) error {
	_, err := q.db.ExecContext(ctx, updateNextRetry, arg.ID, arg.NextRetryAt)
	return err
}
