// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRecoveryCase = `-- name: CreateRecoveryCase :one
INSERT INTO recovery_cases (
    customer_id, subscription_id, payment_id, razorpay_error_code, 
    razorpay_error_desc, amount_at_risk, currency, first_failed_at, recovery_deadline
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW() + INTERVAL '14 days'
)
RETURNING id
`

type CreateRecoveryCaseParams struct {
	CustomerID        uuid.NullUUID  `json:"customer_id"`
	SubscriptionID    string         `json:"subscription_id"`
	PaymentID         sql.NullString `json:"payment_id"`
	RazorpayErrorCode sql.NullString `json:"razorpay_error_code"`
	RazorpayErrorDesc sql.NullString `json:"razorpay_error_desc"`
	AmountAtRisk      int64          `json:"amount_at_risk"`
	Currency          string         `json:"currency"`
}

func (q *Queries) CreateRecoveryCase(ctx context.Context, arg CreateRecoveryCaseParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRecoveryCase,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.PaymentID,
		arg.RazorpayErrorCode,
		arg.RazorpayErrorDesc,
		arg.AmountAtRisk,
		arg.Currency,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveCaseBySubscription = `-- name: GetActiveCaseBySubscription :one
SELECT id, status FROM recovery_cases
WHERE subscription_id = $1 AND status NOT IN ('RECOVERED', 'UNRECOVERABLE', 'EXPIRED')
LIMIT 1
`

type GetActiveCaseBySubscriptionRow struct {
	ID     uuid.UUID      `json:"id"`
	Status RecoveryStatus `json:"status"`
}

func (q *Queries) GetActiveCaseBySubscription(ctx context.Context, subscriptionID string) (GetActiveCaseBySubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveCaseBySubscription, subscriptionID)
	var i GetActiveCaseBySubscriptionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getCaseSummary = `-- name: GetCaseSummary :one
SELECT c.id, c.customer_id, c.subscription_id, c.payment_id, c.razorpay_error_code, c.razorpay_error_desc, c.decline_category, c.ai_diagnosis, c.ai_confidence, c.status, c.retry_count, c.max_retries, c.contact_count, c.max_contacts, c.amount_at_risk, c.currency, c.amount_recovered, c.first_failed_at, c.recovery_deadline, c.recovered_at, c.next_retry_at, c.created_at, c.updated_at, c.ai_strategy, 
       a.action_type AS latest_action_type, 
       a.status AS latest_action_status,
       a.channel AS latest_action_channel
FROM recovery_cases c
LEFT JOIN LATERAL (
    SELECT action_type, status, channel
    FROM recovery_actions
    WHERE recovery_case_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
WHERE c.id = $1 LIMIT 1
`

type GetCaseSummaryRow struct {
	ID                  uuid.UUID             `json:"id"`
	CustomerID          uuid.NullUUID         `json:"customer_id"`
	SubscriptionID      string                `json:"subscription_id"`
	PaymentID           sql.NullString        `json:"payment_id"`
	RazorpayErrorCode   sql.NullString        `json:"razorpay_error_code"`
	RazorpayErrorDesc   sql.NullString        `json:"razorpay_error_desc"`
	DeclineCategory     NullDeclineType       `json:"decline_category"`
	AiDiagnosis         sql.NullString        `json:"ai_diagnosis"`
	AiConfidence        sql.NullFloat64       `json:"ai_confidence"`
	Status              RecoveryStatus        `json:"status"`
	RetryCount          int32                 `json:"retry_count"`
	MaxRetries          int32                 `json:"max_retries"`
	ContactCount        int32                 `json:"contact_count"`
	MaxContacts         int32                 `json:"max_contacts"`
	AmountAtRisk        int64                 `json:"amount_at_risk"`
	Currency            string                `json:"currency"`
	AmountRecovered     sql.NullInt64         `json:"amount_recovered"`
	FirstFailedAt       time.Time             `json:"first_failed_at"`
	RecoveryDeadline    time.Time             `json:"recovery_deadline"`
	RecoveredAt         sql.NullTime          `json:"recovered_at"`
	NextRetryAt         sql.NullTime          `json:"next_retry_at"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
	AiStrategy          pqtype.NullRawMessage `json:"ai_strategy"`
	LatestActionType    ActionType            `json:"latest_action_type"`
	LatestActionStatus  ActionStatus          `json:"latest_action_status"`
	LatestActionChannel sql.NullString        `json:"latest_action_channel"`
}

func (q *Queries) GetCaseSummary(ctx context.Context, id uuid.UUID) (GetCaseSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCaseSummary, id)
	var i GetCaseSummaryRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.PaymentID,
		&i.RazorpayErrorCode,
		&i.RazorpayErrorDesc,
		&i.DeclineCategory,
		&i.AiDiagnosis,
		&i.AiConfidence,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ContactCount,
		&i.MaxContacts,
		&i.AmountAtRisk,
		&i.Currency,
		&i.AmountRecovered,
		&i.FirstFailedAt,
		&i.RecoveryDeadline,
		&i.RecoveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiStrategy,
		&i.LatestActionType,
		&i.LatestActionStatus,
		&i.LatestActionChannel,
	)
	return i, err
}

const getRecoveryCaseByID = `-- name: GetRecoveryCaseByID :one
SELECT id, customer_id, subscription_id, payment_id, razorpay_error_code, razorpay_error_desc, decline_category, ai_diagnosis, ai_confidence, status, retry_count, max_retries, contact_count, max_contacts, amount_at_risk, currency, amount_recovered, first_failed_at, recovery_deadline, recovered_at, next_retry_at, created_at, updated_at, ai_strategy FROM recovery_cases WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecoveryCaseByID(ctx context.Context, id uuid.UUID) (RecoveryCase, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryCaseByID, id)
	var i RecoveryCase
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.PaymentID,
		&i.RazorpayErrorCode,
		&i.RazorpayErrorDesc,
		&i.DeclineCategory,
		&i.AiDiagnosis,
		&i.AiConfidence,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ContactCount,
		&i.MaxContacts,
		&i.AmountAtRisk,
		&i.Currency,
		&i.AmountRecovered,
		&i.FirstFailedAt,
		&i.RecoveryDeadline,
		&i.RecoveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiStrategy,
	)
	return i, err
}

const listPendingCases = `-- name: ListPendingCases :many
SELECT c.id, c.customer_id, c.subscription_id, c.payment_id, c.razorpay_error_code, c.razorpay_error_desc, c.decline_category, c.ai_diagnosis, c.ai_confidence, c.status, c.retry_count, c.max_retries, c.contact_count, c.max_contacts, c.amount_at_risk, c.currency, c.amount_recovered, c.first_failed_at, c.recovery_deadline, c.recovered_at, c.next_retry_at, c.created_at, c.updated_at, c.ai_strategy, 
       a.action_type AS latest_action_type, 
       a.status AS latest_action_status,
       a.channel AS latest_action_channel
FROM recovery_cases c
JOIN LATERAL (
    SELECT action_type, status, channel
    FROM recovery_actions
    WHERE recovery_case_id = c.id
      AND status = 'PENDING_APPROVAL'
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
WHERE EXISTS (
    SELECT 1 FROM recovery_actions ra 
    WHERE ra.recovery_case_id = c.id AND ra.status = 'PENDING_APPROVAL'
)
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingCasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingCasesRow struct {
	ID                  uuid.UUID             `json:"id"`
	CustomerID          uuid.NullUUID         `json:"customer_id"`
	SubscriptionID      string                `json:"subscription_id"`
	PaymentID           sql.NullString        `json:"payment_id"`
	RazorpayErrorCode   sql.NullString        `json:"razorpay_error_code"`
	RazorpayErrorDesc   sql.NullString        `json:"razorpay_error_desc"`
	DeclineCategory     NullDeclineType       `json:"decline_category"`
	AiDiagnosis         sql.NullString        `json:"ai_diagnosis"`
	AiConfidence        sql.NullFloat64       `json:"ai_confidence"`
	Status              RecoveryStatus        `json:"status"`
	RetryCount          int32                 `json:"retry_count"`
	MaxRetries          int32                 `json:"max_retries"`
	ContactCount        int32                 `json:"contact_count"`
	MaxContacts         int32                 `json:"max_contacts"`
	AmountAtRisk        int64                 `json:"amount_at_risk"`
	Currency            string                `json:"currency"`
	AmountRecovered     sql.NullInt64         `json:"amount_recovered"`
	FirstFailedAt       time.Time             `json:"first_failed_at"`
	RecoveryDeadline    time.Time             `json:"recovery_deadline"`
	RecoveredAt         sql.NullTime          `json:"recovered_at"`
	NextRetryAt         sql.NullTime          `json:"next_retry_at"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
	AiStrategy          pqtype.NullRawMessage `json:"ai_strategy"`
	LatestActionType    ActionType            `json:"latest_action_type"`
	LatestActionStatus  ActionStatus          `json:"latest_action_status"`
	LatestActionChannel sql.NullString        `json:"latest_action_channel"`
}

func (q *Queries) ListPendingCases(ctx context.Context, arg ListPendingCasesParams) ([]ListPendingCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingCasesRow
	for rows.Next() {
		var i ListPendingCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.PaymentID,
			&i.RazorpayErrorCode,
			&i.RazorpayErrorDesc,
			&i.DeclineCategory,
			&i.AiDiagnosis,
			&i.AiConfidence,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ContactCount,
			&i.MaxContacts,
			&i.AmountAtRisk,
			&i.Currency,
			&i.AmountRecovered,
			&i.FirstFailedAt,
			&i.RecoveryDeadline,
			&i.RecoveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AiStrategy,
			&i.LatestActionType,
			&i.LatestActionStatus,
			&i.LatestActionChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveredCases = `-- name: ListRecoveredCases :many
SELECT 
    c.id,
    c.subscription_id,
    c.payment_id,
    c.amount_at_risk,
    c.amount_recovered,
    c.currency,
    c.recovered_at,
    c.created_at,
    cust.name      AS customer_name,
    cust.email     AS customer_email,
    cust.value_tier AS customer_tier,
    COALESCE(a.channel::text, '')::text AS recovery_channel,
    COALESCE(a.action_type::text, '')::text AS recovery_action_type,
    COALESCE(a.discount_percentage, 0)::int AS discount_percentage
FROM recovery_cases c
LEFT JOIN customers cust ON cust.id = c.customer_id
LEFT JOIN LATERAL (
    SELECT channel, action_type, discount_percentage
    FROM recovery_actions
    WHERE recovery_case_id = c.id
      AND status = 'EXECUTED'
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
WHERE c.status = 'RECOVERED'
ORDER BY c.recovered_at DESC
LIMIT $1 OFFSET $2
`

type ListRecoveredCasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecoveredCasesRow struct {
	ID                 uuid.UUID      `json:"id"`
	SubscriptionID     string         `json:"subscription_id"`
	PaymentID          sql.NullString `json:"payment_id"`
	AmountAtRisk       int64          `json:"amount_at_risk"`
	AmountRecovered    sql.NullInt64  `json:"amount_recovered"`
	Currency           string         `json:"currency"`
	RecoveredAt        sql.NullTime   `json:"recovered_at"`
	CreatedAt          time.Time      `json:"created_at"`
	CustomerName       sql.NullString `json:"customer_name"`
	CustomerEmail      sql.NullString `json:"customer_email"`
	CustomerTier       sql.NullString `json:"customer_tier"`
	RecoveryChannel    string         `json:"recovery_channel"`
	RecoveryActionType string         `json:"recovery_action_type"`
	DiscountPercentage int32          `json:"discount_percentage"`
}

func (q *Queries) ListRecoveredCases(ctx context.Context, arg ListRecoveredCasesParams) ([]ListRecoveredCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveredCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecoveredCasesRow
	for rows.Next() {
		var i ListRecoveredCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.PaymentID,
			&i.AmountAtRisk,
			&i.AmountRecovered,
			&i.Currency,
			&i.RecoveredAt,
			&i.CreatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerTier,
			&i.RecoveryChannel,
			&i.RecoveryActionType,
			&i.DiscountPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryCases = `-- name: ListRecoveryCases :many
SELECT c.id, c.customer_id, c.subscription_id, c.payment_id, c.razorpay_error_code, c.razorpay_error_desc, c.decline_category, c.ai_diagnosis, c.ai_confidence, c.status, c.retry_count, c.max_retries, c.contact_count, c.max_contacts, c.amount_at_risk, c.currency, c.amount_recovered, c.first_failed_at, c.recovery_deadline, c.recovered_at, c.next_retry_at, c.created_at, c.updated_at, c.ai_strategy, 
       a.action_type AS latest_action_type, 
       a.status AS latest_action_status,
       a.channel AS latest_action_channel
FROM recovery_cases c
LEFT JOIN LATERAL (
    SELECT action_type, status, channel
    FROM recovery_actions
    WHERE recovery_case_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecoveryCasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecoveryCasesRow struct {
	ID                  uuid.UUID             `json:"id"`
	CustomerID          uuid.NullUUID         `json:"customer_id"`
	SubscriptionID      string                `json:"subscription_id"`
	PaymentID           sql.NullString        `json:"payment_id"`
	RazorpayErrorCode   sql.NullString        `json:"razorpay_error_code"`
	RazorpayErrorDesc   sql.NullString        `json:"razorpay_error_desc"`
	DeclineCategory     NullDeclineType       `json:"decline_category"`
	AiDiagnosis         sql.NullString        `json:"ai_diagnosis"`
	AiConfidence        sql.NullFloat64       `json:"ai_confidence"`
	Status              RecoveryStatus        `json:"status"`
	RetryCount          int32                 `json:"retry_count"`
	MaxRetries          int32                 `json:"max_retries"`
	ContactCount        int32                 `json:"contact_count"`
	MaxContacts         int32                 `json:"max_contacts"`
	AmountAtRisk        int64                 `json:"amount_at_risk"`
	Currency            string                `json:"currency"`
	AmountRecovered     sql.NullInt64         `json:"amount_recovered"`
	FirstFailedAt       time.Time             `json:"first_failed_at"`
	RecoveryDeadline    time.Time             `json:"recovery_deadline"`
	RecoveredAt         sql.NullTime          `json:"recovered_at"`
	NextRetryAt         sql.NullTime          `json:"next_retry_at"`
	CreatedAt           time.Time             `json:"created_at"`
	UpdatedAt           time.Time             `json:"updated_at"`
	AiStrategy          pqtype.NullRawMessage `json:"ai_strategy"`
	LatestActionType    ActionType            `json:"latest_action_type"`
	LatestActionStatus  ActionStatus          `json:"latest_action_status"`
	LatestActionChannel sql.NullString        `json:"latest_action_channel"`
}

func (q *Queries) ListRecoveryCases(ctx context.Context, arg ListRecoveryCasesParams) ([]ListRecoveryCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveryCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecoveryCasesRow
	for rows.Next() {
		var i ListRecoveryCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.PaymentID,
			&i.RazorpayErrorCode,
			&i.RazorpayErrorDesc,
			&i.DeclineCategory,
			&i.AiDiagnosis,
			&i.AiConfidence,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ContactCount,
			&i.MaxContacts,
			&i.AmountAtRisk,
			&i.Currency,
			&i.AmountRecovered,
			&i.FirstFailedAt,
			&i.RecoveryDeadline,
			&i.RecoveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AiStrategy,
			&i.LatestActionType,
			&i.LatestActionStatus,
			&i.LatestActionChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseDiagnosis = `-- name: UpdateCaseDiagnosis :exec
UPDATE recovery_cases
SET ai_diagnosis = $2, ai_confidence = $3, decline_category = $4, status = 'DIAGNOSING', updated_at = NOW()
WHERE id = $1
`

type UpdateCaseDiagnosisParams struct {
	ID              uuid.UUID       `json:"id"`
	AiDiagnosis     sql.NullString  `json:"ai_diagnosis"`
	AiConfidence    sql.NullFloat64 `json:"ai_confidence"`
	DeclineCategory NullDeclineType `json:"decline_category"`
}

func (q *Queries) UpdateCaseDiagnosis(ctx context.Context, arg UpdateCaseDiagnosisParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseDiagnosis,
		arg.ID,
		arg.AiDiagnosis,
		arg.AiConfidence,
		arg.DeclineCategory,
	)
	return err
}

const updateCaseRecovered = `-- name: UpdateCaseRecovered :exec
UPDATE recovery_cases
SET status = 'RECOVERED', amount_recovered = $2, recovered_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateCaseRecoveredParams struct {
	ID              uuid.UUID     `json:"id"`
	AmountRecovered sql.NullInt64 `json:"amount_recovered"`
}

func (q *Queries) UpdateCaseRecovered(ctx context.Context, arg UpdateCaseRecoveredParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseRecovered, arg.ID, arg.AmountRecovered)
	return err
}

const updateCaseStatus = `-- name: UpdateCaseStatus :exec
UPDATE recovery_cases
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCaseStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status RecoveryStatus `json:"status"`
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseStatus, arg.ID, arg.Status)
	return err
}

const updateCaseStrategy = `-- name: UpdateCaseStrategy :exec
UPDATE recovery_cases
SET ai_strategy = $2, status = 'RECOVERING', updated_at = NOW()
WHERE id = $1
`

type UpdateCaseStrategyParams struct {
	ID         uuid.UUID             `json:"id"`
	AiStrategy pqtype.NullRawMessage `json:"ai_strategy"`
}

func (q *Queries) UpdateCaseStrategy(ctx context.Context, arg UpdateCaseStrategyParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseStrategy, arg.ID, arg.AiStrategy)
	return err
}

const updateNextRetry = `-- name: UpdateNextRetry :exec
UPDATE recovery_cases
SET next_retry_at = $2, retry_count = retry_count + 1, updated_at = NOW()
WHERE id = $1
`

type UpdateNextRetryParams struct {
	ID          uuid.UUID    `json:"id"`
	NextRetryAt sql.NullTime `json:"next_retry_at"`
}

func (q *Queries) UpdateNextRetry(ctx context.Context, arg UpdateNextRetryParams) error {
	_, err := q.db.ExecContext(ctx, updateNextRetry, arg.ID, arg.NextRetryAt)
	return err
}
