// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communication.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCommunicationHistory = `-- name: GetCommunicationHistory :many
SELECT id, recovery_case_id, customer_id, channel, status, message_sid, sent_at, delivered_at, opened_at, clicked_at
FROM communication_history
WHERE customer_id = (SELECT id FROM customers WHERE razorpay_customer_id = $1 LIMIT 1)
ORDER BY sent_at DESC LIMIT 5
`

func (q *Queries) GetCommunicationHistory(ctx context.Context, razorpayCustomerID sql.NullString) ([]CommunicationHistory, error) {
	rows, err := q.db.QueryContext(ctx, getCommunicationHistory, razorpayCustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunicationHistory
	for rows.Next() {
		var i CommunicationHistory
		if err := rows.Scan(
			&i.ID,
			&i.RecoveryCaseID,
			&i.CustomerID,
			&i.Channel,
			&i.Status,
			&i.MessageSid,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommunicationHistory = `-- name: InsertCommunicationHistory :one
INSERT INTO communication_history (recovery_case_id, customer_id, channel, message_sid)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertCommunicationHistoryParams struct {
	RecoveryCaseID uuid.UUID      `json:"recovery_case_id"`
	CustomerID     uuid.UUID      `json:"customer_id"`
	Channel        string         `json:"channel"`
	MessageSid     sql.NullString `json:"message_sid"`
}

func (q *Queries) InsertCommunicationHistory(ctx context.Context, arg InsertCommunicationHistoryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertCommunicationHistory,
		arg.RecoveryCaseID,
		arg.CustomerID,
		arg.Channel,
		arg.MessageSid,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCommunicationStatus = `-- name: UpdateCommunicationStatus :exec
UPDATE communication_history
SET status = $2, delivered_at = CASE WHEN $2 = 'DELIVERED' THEN NOW() ELSE delivered_at END,
opened_at = CASE WHEN $2 = 'OPENED' THEN NOW() ELSE opened_at END,
clicked_at = CASE WHEN $2 = 'CLICKED' THEN NOW() ELSE clicked_at END
WHERE message_sid = $1
`

type UpdateCommunicationStatusParams struct {
	MessageSid sql.NullString `json:"message_sid"`
	Status     string         `json:"status"`
}

func (q *Queries) UpdateCommunicationStatus(ctx context.Context, arg UpdateCommunicationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCommunicationStatus, arg.MessageSid, arg.Status)
	return err
}
