// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT 
    id, razorpay_customer_id, name, value_tier, tenure, 
    preferred_channel, city, state, failed_payments, reliability_score
FROM customers
WHERE razorpay_customer_id = $1 LIMIT 1
`

type GetCustomerProfileRow struct {
	ID                 uuid.UUID      `json:"id"`
	RazorpayCustomerID sql.NullString `json:"razorpay_customer_id"`
	Name               sql.NullString `json:"name"`
	ValueTier          sql.NullString `json:"value_tier"`
	Tenure             sql.NullString `json:"tenure"`
	PreferredChannel   sql.NullString `json:"preferred_channel"`
	City               sql.NullString `json:"city"`
	State              sql.NullString `json:"state"`
	FailedPayments     int32          `json:"failed_payments"`
	ReliabilityScore   float64        `json:"reliability_score"`
}

func (q *Queries) GetCustomerProfile(ctx context.Context, razorpayCustomerID sql.NullString) (GetCustomerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerProfile, razorpayCustomerID)
	var i GetCustomerProfileRow
	err := row.Scan(
		&i.ID,
		&i.RazorpayCustomerID,
		&i.Name,
		&i.ValueTier,
		&i.Tenure,
		&i.PreferredChannel,
		&i.City,
		&i.State,
		&i.FailedPayments,
		&i.ReliabilityScore,
	)
	return i, err
}

const incrementFailedPayment = `-- name: IncrementFailedPayment :exec
UPDATE customers
SET failed_payments = failed_payments + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementFailedPayment, id)
	return err
}

const incrementSuccessfulPayment = `-- name: IncrementSuccessfulPayment :exec
UPDATE customers
SET successful_payments = successful_payments + 1, total_payments = total_payments + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementSuccessfulPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementSuccessfulPayment, id)
	return err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customers (
    razorpay_customer_id, email, phone, name, value_tier, tenure, preferred_channel, city, state
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (razorpay_customer_id) DO UPDATE 
SET email = EXCLUDED.email, phone = EXCLUDED.phone, name = EXCLUDED.name, updated_at = NOW()
RETURNING id
`

type InsertCustomerParams struct {
	RazorpayCustomerID sql.NullString `json:"razorpay_customer_id"`
	Email              sql.NullString `json:"email"`
	Phone              sql.NullString `json:"phone"`
	Name               sql.NullString `json:"name"`
	ValueTier          sql.NullString `json:"value_tier"`
	Tenure             sql.NullString `json:"tenure"`
	PreferredChannel   sql.NullString `json:"preferred_channel"`
	City               sql.NullString `json:"city"`
	State              sql.NullString `json:"state"`
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertCustomer,
		arg.RazorpayCustomerID,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.ValueTier,
		arg.Tenure,
		arg.PreferredChannel,
		arg.City,
		arg.State,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
