// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const getChannelDistribution = `-- name: GetChannelDistribution :many
SELECT 
    channel,
    COUNT(*)::INT as count
FROM recovery_actions
WHERE channel IS NOT NULL
GROUP BY channel
ORDER BY count DESC
`

type GetChannelDistributionRow struct {
	Channel sql.NullString `json:"channel"`
	Count   int32          `json:"count"`
}

func (q *Queries) GetChannelDistribution(ctx context.Context) ([]GetChannelDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelDistributionRow
	for rows.Next() {
		var i GetChannelDistributionRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardOverview = `-- name: GetDashboardOverview :one
SELECT 
    COALESCE(SUM(amount_at_risk), 0)::BIGINT as total_amount_at_risk,
    COALESCE(SUM(amount_recovered), 0)::BIGINT as total_amount_recovered,
    COUNT(CASE WHEN status = 'RECOVERED' THEN 1 END)::INT as recovered_cases_count,
    COUNT(CASE WHEN status IN ('DETECTED', 'DIAGNOSING', 'RECOVERING') THEN 1 END)::INT as active_cases_count,
    COUNT(CASE WHEN status IN ('UNRECOVERABLE', 'EXPIRED', 'ESCALATED') THEN 1 END)::INT as failed_cases_count
FROM recovery_cases
`

type GetDashboardOverviewRow struct {
	TotalAmountAtRisk    int64 `json:"total_amount_at_risk"`
	TotalAmountRecovered int64 `json:"total_amount_recovered"`
	RecoveredCasesCount  int32 `json:"recovered_cases_count"`
	ActiveCasesCount     int32 `json:"active_cases_count"`
	FailedCasesCount     int32 `json:"failed_cases_count"`
}

func (q *Queries) GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardOverview)
	var i GetDashboardOverviewRow
	err := row.Scan(
		&i.TotalAmountAtRisk,
		&i.TotalAmountRecovered,
		&i.RecoveredCasesCount,
		&i.ActiveCasesCount,
		&i.FailedCasesCount,
	)
	return i, err
}

const getPipelineStatus = `-- name: GetPipelineStatus :many
SELECT 
    status,
    COUNT(*)::INT as count
FROM recovery_actions
GROUP BY status
ORDER BY count DESC
`

type GetPipelineStatusRow struct {
	Status ActionStatus `json:"status"`
	Count  int32        `json:"count"`
}

func (q *Queries) GetPipelineStatus(ctx context.Context) ([]GetPipelineStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getPipelineStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPipelineStatusRow
	for rows.Next() {
		var i GetPipelineStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecoveryTrends = `-- name: GetRecoveryTrends :many
SELECT 
    DATE_TRUNC('day', created_at)::DATE as date,
    COALESCE(SUM(amount_at_risk), 0)::BIGINT as daily_failed,
    COALESCE(SUM(amount_recovered), 0)::BIGINT as daily_recovered
FROM recovery_cases
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY date ASC
`

type GetRecoveryTrendsRow struct {
	Date           time.Time `json:"date"`
	DailyFailed    int64     `json:"daily_failed"`
	DailyRecovered int64     `json:"daily_recovered"`
}

func (q *Queries) GetRecoveryTrends(ctx context.Context) ([]GetRecoveryTrendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecoveryTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecoveryTrendsRow
	for rows.Next() {
		var i GetRecoveryTrendsRow
		if err := rows.Scan(&i.Date, &i.DailyFailed, &i.DailyRecovered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
