// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActionStatus string

const (
	ActionStatusPENDING         ActionStatus = "PENDING"
	ActionStatusEXECUTED        ActionStatus = "EXECUTED"
	ActionStatusFAILED          ActionStatus = "FAILED"
	ActionStatusBLOCKEDBYPOLICY ActionStatus = "BLOCKED_BY_POLICY"
	ActionStatusPENDINGAPPROVAL ActionStatus = "PENDING_APPROVAL"
	ActionStatusAPPROVED        ActionStatus = "APPROVED"
	ActionStatusREJECTED        ActionStatus = "REJECTED"
)

func (e *ActionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionStatus(s)
	case string:
		*e = ActionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionStatus: %T", src)
	}
	return nil
}

type NullActionStatus struct {
	ActionStatus ActionStatus `json:"action_status"`
	Valid        bool         `json:"valid"` // Valid is true if ActionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ActionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionStatus), nil
}

type ActionType string

const (
	ActionTypeSILENTRETRY       ActionType = "SILENT_RETRY"
	ActionTypeSENDPAYMENTLINK   ActionType = "SEND_PAYMENT_LINK"
	ActionTypeSENDEMAIL         ActionType = "SEND_EMAIL"
	ActionTypeSENDSMS           ActionType = "SEND_SMS"
	ActionTypeSENDWHATSAPP      ActionType = "SEND_WHATSAPP"
	ActionTypeESCALATETOHUMAN   ActionType = "ESCALATE_TO_HUMAN"
	ActionTypeMARKUNRECOVERABLE ActionType = "MARK_UNRECOVERABLE"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType `json:"action_type"`
	Valid      bool       `json:"valid"` // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type DeclineType string

const (
	DeclineTypeSOFT      DeclineType = "SOFT"
	DeclineTypeHARD      DeclineType = "HARD"
	DeclineTypeAMBIGUOUS DeclineType = "AMBIGUOUS"
)

func (e *DeclineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeclineType(s)
	case string:
		*e = DeclineType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeclineType: %T", src)
	}
	return nil
}

type NullDeclineType struct {
	DeclineType DeclineType `json:"decline_type"`
	Valid       bool        `json:"valid"` // Valid is true if DeclineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeclineType) Scan(value interface{}) error {
	if value == nil {
		ns.DeclineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeclineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeclineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeclineType), nil
}

type RecoveryStatus string

const (
	RecoveryStatusDETECTED      RecoveryStatus = "DETECTED"
	RecoveryStatusDIAGNOSING    RecoveryStatus = "DIAGNOSING"
	RecoveryStatusRECOVERING    RecoveryStatus = "RECOVERING"
	RecoveryStatusRECOVERED     RecoveryStatus = "RECOVERED"
	RecoveryStatusESCALATED     RecoveryStatus = "ESCALATED"
	RecoveryStatusUNRECOVERABLE RecoveryStatus = "UNRECOVERABLE"
	RecoveryStatusEXPIRED       RecoveryStatus = "EXPIRED"
)

func (e *RecoveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecoveryStatus(s)
	case string:
		*e = RecoveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecoveryStatus: %T", src)
	}
	return nil
}

type NullRecoveryStatus struct {
	RecoveryStatus RecoveryStatus `json:"recovery_status"`
	Valid          bool           `json:"valid"` // Valid is true if RecoveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecoveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecoveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecoveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecoveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecoveryStatus), nil
}

type AuditLog struct {
	ID           int64           `json:"id"`
	SourceBinary string          `json:"source_binary"`
	EventType    string          `json:"event_type"`
	Actor        sql.NullString  `json:"actor"`
	TraceID      uuid.NullUUID   `json:"trace_id"`
	EntityID     sql.NullString  `json:"entity_id"`
	Payload      json.RawMessage `json:"payload"`
	CreatedAt    time.Time       `json:"created_at"`
}

type CommunicationHistory struct {
	ID             uuid.UUID      `json:"id"`
	RecoveryCaseID uuid.UUID      `json:"recovery_case_id"`
	CustomerID     uuid.UUID      `json:"customer_id"`
	Channel        string         `json:"channel"`
	Status         string         `json:"status"`
	MessageSid     sql.NullString `json:"message_sid"`
	SentAt         time.Time      `json:"sent_at"`
	DeliveredAt    sql.NullTime   `json:"delivered_at"`
	OpenedAt       sql.NullTime   `json:"opened_at"`
	ClickedAt      sql.NullTime   `json:"clicked_at"`
}

type Customer struct {
	ID                 uuid.UUID      `json:"id"`
	RazorpayCustomerID sql.NullString `json:"razorpay_customer_id"`
	Email              sql.NullString `json:"email"`
	Phone              sql.NullString `json:"phone"`
	Name               sql.NullString `json:"name"`
	ValueTier          sql.NullString `json:"value_tier"`
	Tenure             sql.NullString `json:"tenure"`
	PreferredChannel   sql.NullString `json:"preferred_channel"`
	TotalPayments      int32          `json:"total_payments"`
	SuccessfulPayments int32          `json:"successful_payments"`
	FailedPayments     int32          `json:"failed_payments"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	City               sql.NullString `json:"city"`
	State              sql.NullString `json:"state"`
	ReliabilityScore   float64        `json:"reliability_score"`
}

type RecoveryAction struct {
	ID                   uuid.UUID       `json:"id"`
	RecoveryCaseID       uuid.UUID       `json:"recovery_case_id"`
	IdempotencyKey       string          `json:"idempotency_key"`
	ActionType           ActionType      `json:"action_type"`
	Channel              sql.NullString  `json:"channel"`
	AiReasoning          sql.NullString  `json:"ai_reasoning"`
	AiConfidence         sql.NullFloat64 `json:"ai_confidence"`
	PolicyApproved       bool            `json:"policy_approved"`
	PolicyBlockReason    sql.NullString  `json:"policy_block_reason"`
	Status               ActionStatus    `json:"status"`
	ExternalID           sql.NullString  `json:"external_id"`
	ErrorMessage         sql.NullString  `json:"error_message"`
	PaymentLinkID        sql.NullString  `json:"payment_link_id"`
	PaymentLinkUrl       sql.NullString  `json:"payment_link_url"`
	PaymentLinkExpiresAt sql.NullTime    `json:"payment_link_expires_at"`
	ExecutedAt           sql.NullTime    `json:"executed_at"`
	CreatedAt            time.Time       `json:"created_at"`
	DiscountPercentage   sql.NullInt32   `json:"discount_percentage"`
	DraftSubject         sql.NullString  `json:"draft_subject"`
	DraftBody            sql.NullString  `json:"draft_body"`
	AsynqTaskID          sql.NullString  `json:"asynq_task_id"`
	ApprovedByClerkID    sql.NullString  `json:"approved_by_clerk_id"`
}

type RecoveryCase struct {
	ID                uuid.UUID             `json:"id"`
	CustomerID        uuid.NullUUID         `json:"customer_id"`
	SubscriptionID    string                `json:"subscription_id"`
	PaymentID         sql.NullString        `json:"payment_id"`
	RazorpayErrorCode sql.NullString        `json:"razorpay_error_code"`
	RazorpayErrorDesc sql.NullString        `json:"razorpay_error_desc"`
	DeclineCategory   NullDeclineType       `json:"decline_category"`
	AiDiagnosis       sql.NullString        `json:"ai_diagnosis"`
	AiConfidence      sql.NullFloat64       `json:"ai_confidence"`
	Status            RecoveryStatus        `json:"status"`
	RetryCount        int32                 `json:"retry_count"`
	MaxRetries        int32                 `json:"max_retries"`
	ContactCount      int32                 `json:"contact_count"`
	MaxContacts       int32                 `json:"max_contacts"`
	AmountAtRisk      int64                 `json:"amount_at_risk"`
	Currency          string                `json:"currency"`
	AmountRecovered   sql.NullInt64         `json:"amount_recovered"`
	FirstFailedAt     time.Time             `json:"first_failed_at"`
	RecoveryDeadline  time.Time             `json:"recovery_deadline"`
	RecoveredAt       sql.NullTime          `json:"recovered_at"`
	NextRetryAt       sql.NullTime          `json:"next_retry_at"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
	AiStrategy        pqtype.NullRawMessage `json:"ai_strategy"`
}

type WebhookEvent struct {
	ID              uuid.UUID       `json:"id"`
	RazorpayEventID string          `json:"razorpay_event_id"`
	EventType       string          `json:"event_type"`
	Payload         json.RawMessage `json:"payload"`
	Signature       string          `json:"signature"`
	Processed       bool            `json:"processed"`
	ProcessedAt     sql.NullTime    `json:"processed_at"`
	CreatedAt       time.Time       `json:"created_at"`
}
