// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveAction(ctx context.Context, arg ApproveActionParams) error
	CreateRecoveryAction(ctx context.Context, arg CreateRecoveryActionParams) (uuid.UUID, error)
	CreateRecoveryCase(ctx context.Context, arg CreateRecoveryCaseParams) (uuid.UUID, error)
	GetActionAndCaseForApproval(ctx context.Context, id uuid.UUID) (GetActionAndCaseForApprovalRow, error)
	GetActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetActionByIdempotencyKeyRow, error)
	GetActionsByCase(ctx context.Context, recoveryCaseID uuid.UUID) ([]GetActionsByCaseRow, error)
	GetActiveCaseBySubscription(ctx context.Context, subscriptionID string) (GetActiveCaseBySubscriptionRow, error)
	GetCaseSummary(ctx context.Context, id uuid.UUID) (GetCaseSummaryRow, error)
	GetChannelDistribution(ctx context.Context) ([]GetChannelDistributionRow, error)
	GetCommunicationHistory(ctx context.Context, razorpayCustomerID sql.NullString) ([]CommunicationHistory, error)
	GetCustomerByEmailOrPhone(ctx context.Context, arg GetCustomerByEmailOrPhoneParams) (uuid.UUID, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerProfile(ctx context.Context, razorpayCustomerID sql.NullString) (GetCustomerProfileRow, error)
	GetDashboardOverview(ctx context.Context) (GetDashboardOverviewRow, error)
	GetPendingActions(ctx context.Context) ([]GetPendingActionsRow, error)
	GetPipelineStatus(ctx context.Context) ([]GetPipelineStatusRow, error)
	GetRecoveryCaseByID(ctx context.Context, id uuid.UUID) (RecoveryCase, error)
	GetRecoveryTrends(ctx context.Context) ([]GetRecoveryTrendsRow, error)
	IncrementFailedPayment(ctx context.Context, id uuid.UUID) error
	IncrementSuccessfulPayment(ctx context.Context, id uuid.UUID) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCommunicationHistory(ctx context.Context, arg InsertCommunicationHistoryParams) (uuid.UUID, error)
	InsertCustomer(ctx context.Context, arg InsertCustomerParams) (uuid.UUID, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListPendingCases(ctx context.Context, arg ListPendingCasesParams) ([]ListPendingCasesRow, error)
	ListRecoveredCases(ctx context.Context, arg ListRecoveredCasesParams) ([]ListRecoveredCasesRow, error)
	ListRecoveryCases(ctx context.Context, arg ListRecoveryCasesParams) ([]ListRecoveryCasesRow, error)
	LogWebhookEvent(ctx context.Context, arg LogWebhookEventParams) error
	MarkActionExecuted(ctx context.Context, arg MarkActionExecutedParams) error
	RejectAction(ctx context.Context, arg RejectActionParams) error
	UpdateActionAsynqTask(ctx context.Context, arg UpdateActionAsynqTaskParams) error
	UpdateActionDraft(ctx context.Context, arg UpdateActionDraftParams) error
	UpdateCaseDiagnosis(ctx context.Context, arg UpdateCaseDiagnosisParams) error
	UpdateCaseRecovered(ctx context.Context, arg UpdateCaseRecoveredParams) error
	UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) error
	UpdateCaseStrategy(ctx context.Context, arg UpdateCaseStrategyParams) error
	UpdateCommunicationStatus(ctx context.Context, arg UpdateCommunicationStatusParams) error
	UpdateNextRetry(ctx context.Context, arg UpdateNextRetryParams) error
}

var _ Querier = (*Queries)(nil)
