// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package repo

import (
	"context"
	"encoding/json"
)

const logWebhookEvent = `-- name: LogWebhookEvent :exec
INSERT INTO webhook_events (razorpay_event_id, event_type, payload, signature)
VALUES ($1, $2, $3, $4)
`

type LogWebhookEventParams struct {
	RazorpayEventID string          `json:"razorpay_event_id"`
	EventType       string          `json:"event_type"`
	Payload         json.RawMessage `json:"payload"`
	Signature       string          `json:"signature"`
}

func (q *Queries) LogWebhookEvent(ctx context.Context, arg LogWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, logWebhookEvent,
		arg.RazorpayEventID,
		arg.EventType,
		arg.Payload,
		arg.Signature,
	)
	return err
}
